vim.g.mapleader = ' '

require('options')
require('keymaps')
require('lsp')
require('autocmd')
require('plugins.notify')
require('plugins.lualine')
require('plugins.telescope')
require('plugins.gitsigns')
require('plugins.which-key')
require('plugins.comment')
require('plugins.autopairs')
require('plugins.illuminate')
require('plugins.smartcolumn')
require('plugins.luasnip')
require('plugins.blink-cmp')
require('plugins.dapui')
require('plugins.copilot')
require('plugins.codecompanion')
require('plugins.neo-tree')
require('plugins.persistence')
require('plugins.dashboard')
require('plugins.colorizerLua')
require('plugins.noice')
require('plugins.auto-save-nvim')


